spring.application.name=RideShareApp

sspring.thymeleaf.cache=false

spring.servlet.multipart.max-file-size=5MB

spring.profiles.active=prod

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=3cc39263368d16
spring.mail.password=fca19e4217caa8
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.starttls.enable=true